# Base letters with different sound (with/without dagesh)
class Letters:
    ALEF = 'א'
    VET = 'ב'
    BET_DAGESH = 'בּ'
    GIMEL = 'ג'
    GIMEL_DAGESH = 'גּ'
    DALET = 'ד'
    DALET_DAGESH = 'דּ'
    HE = 'ה'
    VAV = 'ו'
    ZAYIN = 'ז'
    HET = 'ח'
    TET = 'ט'
    YOD = 'י'
    HAF = 'כ'
    KAF_DAGESH = 'כּ'
    LAMED = 'ל'
    MEM = 'מ'
    NUN = 'נ'
    SAMEKH = 'ס'
    AYIN = 'ע'
    FEY = 'פ'
    PEY_DAGESH = 'פּ'
    TSADI = 'צ'
    QOF = 'ק'
    RESH = 'ר'
    SHIN = 'ש'
    SHIN_RIGHT_POINT = 'שׁ'
    SIN_LEFT_POINT = 'שׂ'
    TAF = 'ת'
    TAF_DAGESH = 'תּ'

    # Sofiyot with or without Dagesh
    HAF_SOFIT = 'ך'
    KAF_SOFIT_DAGESH = 'ךּ'
    MEM_SOFIT = 'ם'
    NUN_SOFIT = 'ן'
    PE_SOFIT = 'ף'
    PE_SOFIT_DAGESH = 'ףּ'
    TSADI_SOFIT = 'ץ'
    
